import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
padding.x = 10
padding.y = 10

# for mac only
option_as_alt = "both"

[font]
normal.family = "CaskaydiaCove Nerd Font"
size = 16

