unbind-key C-b
unbind-key C-a
set-option -g prefix `
bind-key ` send-prefix

# Get 256 color support
set -g default-terminal "tmux-256color"

set -g extended-keys on
set -g extended-keys-format csi-u

# Window switching - Ctrl+h/l
bind -n C-h previous-window
bind -n C-l next-window
bind -T copy-mode-vi C-h previous-window
bind -T copy-mode-vi C-l next-window

# Reassign prefix+n to create/switch session, disable prefix+p window switch
unbind-key n
unbind-key p
bind-key n command-prompt -p "new session name" "new-session -A -s '%%'"

# Smart pane switching with awareness of Vim/Neovim splits (Alt+hjkl)
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind -n M-h if-shell "$is_vim" 'send-keys M-h' 'select-pane -L'
bind -n M-j if-shell "$is_vim" 'send-keys M-j' 'select-pane -D'
bind -n M-k if-shell "$is_vim" 'send-keys M-k' 'select-pane -U'
bind -n M-l if-shell "$is_vim" 'send-keys M-l' 'select-pane -R'

# Alt-i/o to move current window left/right in order
bind -n M-i swap-window -t -1 \; select-window -t -1
bind -n M-o swap-window -t +1 \; select-window -t +1

# Mouse mode
set -g mouse on

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y if -F "#{selection_present}" {
    send -X copy-selection-and-cancel
} {
    switch-client -T copy-mode-vi-y
}
bind-key -T copy-mode-vi-y y send -X copy-line \; send -X cancel
bind-key -T copy-mode-vi-y w send -X begin-selection \; send -X next-word \; send -X cursor-left \; send -X copy-selection-and-cancel
bind-key -T copy-mode-vi g switch-client -T copy-mode-vi-g
bind-key -T copy-mode-vi-g g send -X history-top
bind-key -T copy-mode-vi-g h send -X start-of-line
bind-key -T copy-mode-vi-g l send -X end-of-line

# Set status bar to bottom
set -g status-position bottom

# Set easier window split keys
bind-key v split-window -h -c "#{pane_current_path}"
bind-key h split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# configuration for nvim
set-option -sg escape-time 10
set-option -g focus-events on

# configuration for nvim - true colors settings
set-option -sa terminal-features ',xterm-256color:RGB'

# osc52
set-option -g set-clipboard on


set -g @rose_pine_variant 'moon'
set -g @rose_pine_only_windows 'on'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'

run ~/.config/tmux/plugins/rose-pine.tmux
